# Generated by Django 4.1.4 on 2023-01-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured',
            new_name='active',
        ),
    ]
